export type ContentType = "service" | "solution" | "incident" | "article" | "faq";
export type SiteLocale = "vi" | "en";

export type ContentRecord = {
  id: string;
  type: ContentType;
  locale: SiteLocale;
  translationKey: string;
  slug: string;
  title: string;
  eyebrow: string;
  summary: string;
  body: string;
  meta: string;
  image: string | null;
  status: "draft" | "published";
  seoTitle: string;
  seoDescription: string;
  sortOrder: number;
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

const now = "2026-08-05T00:00:00.000Z";

function record(
  value: Omit<ContentRecord, "locale" | "translationKey" | "status" | "seoTitle" | "seoDescription" | "publishedAt" | "createdAt" | "updatedAt"> & {
    locale?: SiteLocale;
    translationKey?: string;
    seoTitle?: string;
    seoDescription?: string;
  },
): ContentRecord {
  return {
    ...value,
    locale: value.locale ?? "vi",
    translationKey: value.translationKey ?? value.id,
    status: "published",
    seoTitle: value.seoTitle ?? `${value.title} | AKAIUNSAN`,
    seoDescription: value.seoDescription ?? value.summary,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  };
}

const vietnameseSeedContent: ContentRecord[] = [
  record({
    id: "service-recurring",
    type: "service",
    slug: "ve-sinh-thuong-xuyen",
    title: "Vệ sinh thường xuyên",
    eyebrow: "Dịch vụ cốt lõi",
    summary: "Lịch làm việc ổn định theo ngày, tuần hoặc ca, với phạm vi và tiêu chuẩn được thống nhất từ đầu.",
    body: "Phù hợp với khu vực chung của tòa nhà, dự án chung cư, nhà xưởng cần nhân sự theo ca và căn hộ cần hỗ trợ đều đặn.\n\nAKAIUNSAN khảo sát nhu cầu, lập checklist công việc, bố trí nhân sự và theo dõi chất lượng trong suốt thời gian cung cấp dịch vụ.",
    meta: JSON.stringify({
      highlights: ["Lịch làm việc rõ ràng", "Checklist theo khu vực", "Điều phối nhân sự", "Theo dõi và phản hồi"],
      cta: "Nhận phương án vệ sinh thường xuyên",
    }),
    image: "/images/brand-category-condominium-v1.png",
    sortOrder: 1,
  }),
  record({
    id: "service-periodic",
    type: "service",
    slug: "ve-sinh-dinh-ky",
    title: "Vệ sinh định kỳ",
    eyebrow: "Duy trì chất lượng",
    summary: "Xử lý các hạng mục cần làm sâu theo chu kỳ để duy trì bề mặt, thiết bị và không gian sử dụng.",
    body: "Kế hoạch định kỳ được xây dựng theo đặc điểm công trình và mức độ sử dụng. Các hạng mục, thời gian thực hiện và tiêu chí nghiệm thu được thống nhất trước khi triển khai.",
    meta: JSON.stringify({
      highlights: ["Theo tuần, tháng hoặc quý", "Hạng mục chuyên sâu", "Giảm ảnh hưởng vận hành", "Nghiệm thu rõ ràng"],
      cta: "Trao đổi lịch vệ sinh định kỳ",
    }),
    image: "/images/brand-category-industrial-v1.png",
    sortOrder: 2,
  }),
  record({
    id: "service-deep-clean",
    type: "service",
    slug: "tong-ve-sinh",
    title: "Tổng vệ sinh",
    eyebrow: "Làm sạch chuyên sâu",
    summary: "Giải pháp theo đợt cho căn hộ, khu vực bàn giao hoặc công trình cần khôi phục trạng thái sạch tổng thể.",
    body: "Phạm vi tổng vệ sinh được bóc tách theo từng khu vực, vật liệu và mức độ hiện trạng. Đội ngũ lựa chọn dụng cụ, hóa chất và trình tự phù hợp trước khi thực hiện.",
    meta: JSON.stringify({
      highlights: ["Khảo sát hiện trạng", "Phạm vi theo vật liệu", "Thiết bị phù hợp", "Kiểm tra trước bàn giao"],
      cta: "Yêu cầu khảo sát tổng vệ sinh",
    }),
    image: "/images/brand-category-apartment-v1.png",
    sortOrder: 3,
  }),
  record({
    id: "solution-apartment",
    type: "solution",
    slug: "ve-sinh-can-ho",
    title: "Vệ sinh căn hộ",
    eyebrow: "Không gian sống",
    summary: "Dịch vụ linh hoạt theo buổi hoặc định kỳ, tập trung vào sự chỉn chu, tôn trọng không gian riêng và lịch sinh hoạt.",
    body: "Mỗi căn hộ có diện tích, vật liệu và thói quen sử dụng khác nhau. AKAIUNSAN xác nhận phạm vi trước buổi làm, ưu tiên các khu vực quan trọng và bàn giao lại theo checklist.\n\nPhù hợp với khách hàng cần hỗ trợ hằng tuần, theo lịch cố định hoặc tổng vệ sinh theo thời điểm.",
    meta: JSON.stringify({
      highlights: ["Phòng khách và phòng ngủ", "Bếp và bề mặt sử dụng", "Phòng tắm", "Ban công theo thỏa thuận"],
      cta: "Đặt lịch vệ sinh căn hộ",
      leadType: "apartment",
    }),
    image: "/images/brand-category-apartment-v1.png",
    sortOrder: 3,
  }),
  record({
    id: "solution-condominium",
    type: "solution",
    slug: "ve-sinh-chung-cu",
    title: "Vệ sinh tòa nhà & chung cư",
    eyebrow: "Vận hành tòa nhà",
    summary: "Nhân sự và lịch làm việc được tổ chức quanh lưu lượng cư dân, tiêu chuẩn bàn giao và nhu cầu của ban quản lý.",
    body: "Giải pháp dành cho sảnh, hành lang, thang máy, tiện ích và các khu vực công cộng của dự án. Phạm vi theo ca được chuẩn hóa để đội ngũ phối hợp với vận hành tòa nhà và hạn chế ảnh hưởng đến cư dân.\n\nBáo cáo, phản hồi hiện trường và các hạng mục phát sinh được tập trung theo đầu mối quản lý.",
    meta: JSON.stringify({
      highlights: ["Sảnh và hành lang", "Thang máy và khu tiện ích", "Lịch theo lưu lượng cư dân", "Giám sát và phản hồi"],
      cta: "Yêu cầu khảo sát dự án",
      leadType: "building",
    }),
    image: "/images/brand-category-condominium-v1.png",
    sortOrder: 1,
  }),
  record({
    id: "solution-factory",
    type: "solution",
    slug: "ve-sinh-nha-xuong-khu-cong-nghiep",
    title: "Vệ sinh nhà xưởng & khu công nghiệp",
    eyebrow: "Môi trường sản xuất",
    summary: "Phương án làm sạch theo khu vực, ca vận hành và yêu cầu an toàn của từng nhà máy.",
    body: "Nhà xưởng cần quy trình khác biệt cho lối đi, khu phụ trợ, kho, văn phòng sản xuất và các vùng có yêu cầu kiểm soát riêng. AKAIUNSAN khảo sát luồng vận hành trước khi đề xuất nhân sự, thiết bị và tần suất.\n\nAn toàn, phạm vi cho phép và phối hợp với đầu mối nhà máy được xác định trước khi triển khai.",
    meta: JSON.stringify({
      highlights: ["Lối đi và khu phụ trợ", "Lịch theo ca sản xuất", "Thiết bị công nghiệp", "Tuân thủ yêu cầu an toàn"],
      cta: "Yêu cầu khảo sát nhà xưởng",
      leadType: "factory",
    }),
    image: "/images/brand-category-industrial-v1.png",
    sortOrder: 2,
  }),
  record({
    id: "incident-capture",
    type: "incident",
    slug: "ghi-nhan-du-ngu-canh",
    title: "Ghi nhận đủ ngữ cảnh",
    eyebrow: "Triage",
    summary: "Xác nhận thời điểm, khu vực, mức ảnh hưởng và bằng chứng hiện trường để tránh xử lý sai vấn đề.",
    body: "Mỗi sự vụ cần được ghi nhận tại một đầu mối với đủ thông tin: thời điểm, vị trí, người phản ánh, mức ảnh hưởng và hình ảnh khi phù hợp. Dữ liệu rõ ngay từ đầu giúp giảm vòng hỏi lại và rút ngắn thời gian điều phối.",
    meta: "{}",
    image: null,
    sortOrder: 1,
  }),
  record({
    id: "incident-prioritize",
    type: "incident",
    slug: "phan-loai-muc-uu-tien",
    title: "Phân loại mức ưu tiên",
    eyebrow: "Priority",
    summary: "Ưu tiên trước các tình huống liên quan đến an toàn, gián đoạn vận hành hoặc trải nghiệm người sử dụng.",
    body: "Sự vụ được phân loại theo mức ảnh hưởng thay vì xử lý tuần tự đơn thuần. Nguy cơ trượt ngã, tràn nước, hóa chất hoặc gián đoạn khu vực sử dụng cần được cô lập và điều phối trước các vấn đề thẩm mỹ thông thường.",
    meta: "{}",
    image: null,
    sortOrder: 2,
  }),
  record({
    id: "incident-coordinate",
    type: "incident",
    slug: "dieu-phoi-va-cap-nhat",
    title: "Điều phối và cập nhật",
    eyebrow: "Ownership",
    summary: "Chỉ định người phụ trách, hành động tiếp theo và trạng thái để khách hàng không phải tự đuổi theo thông tin.",
    body: "Mỗi sự vụ cần có một người chịu trách nhiệm điều phối, phương án xử lý và trạng thái cập nhật rõ ràng. Khi cần phối hợp với kỹ thuật, an ninh hoặc ban quản lý, đầu mối dịch vụ vẫn giữ trách nhiệm kết nối thông tin.",
    meta: "{}",
    image: null,
    sortOrder: 3,
  }),
  record({
    id: "incident-close-loop",
    type: "incident",
    slug: "dong-su-vu-va-ngan-lap-lai",
    title: "Đóng sự vụ và ngăn lặp lại",
    eyebrow: "Close the loop",
    summary: "Xác nhận kết quả, lưu nguyên nhân và điều chỉnh checklist, vật tư hoặc SOP khi vấn đề có nguy cơ tái diễn.",
    body: "Sự vụ chỉ được đóng khi kết quả đã được xác nhận. Với vấn đề lặp lại, đội ngũ rà nguyên nhân và cập nhật biện pháp phòng ngừa như điều chỉnh tần suất, checklist, vật tư, hướng dẫn hoặc cách giám sát.",
    meta: "{}",
    image: null,
    sortOrder: 4,
  }),
  record({
    id: "article-cost",
    type: "article",
    slug: "bao-gia-dich-vu-ve-sinh-duoc-tinh-nhu-the-nao",
    title: "Báo giá dịch vụ vệ sinh được tính như thế nào?",
    eyebrow: "Chi phí & phạm vi",
    summary: "Diện tích chỉ là một phần; tần suất, vật liệu, ca làm và yêu cầu thiết bị mới quyết định phương án phù hợp.",
    body: "Một báo giá có trách nhiệm bắt đầu từ phạm vi công việc chứ không chỉ từ diện tích. Đơn vị cung cấp cần hiểu loại bề mặt, mật độ sử dụng, thời gian được phép thi công, yêu cầu an toàn và tiêu chí nghiệm thu.\n\nVới tòa nhà và nhà xưởng, bài toán bao gồm ca làm, lưu lượng người, máy móc và cách tổ chức nhân sự. Với căn hộ, số phòng và mức độ hiện trạng ảnh hưởng trực tiếp đến thời lượng.\n\nKhảo sát giúp hai bên thống nhất những gì nằm trong dịch vụ, tần suất và cách xử lý phát sinh trước khi chốt chi phí.",
    meta: "{}",
    image: "/images/brand-insight-pricing-scope-v1.png",
    sortOrder: 1,
  }),
  record({
    id: "article-checklist",
    type: "article",
    slug: "checklist-danh-gia-nha-cung-cap-ve-sinh",
    title: "Checklist đánh giá nhà cung cấp dịch vụ vệ sinh",
    eyebrow: "Lựa chọn đối tác",
    summary: "Sáu câu hỏi giúp ban quản lý và nhà máy đánh giá năng lực tổ chức thay vì chỉ so sánh đơn giá.",
    body: "Hãy bắt đầu bằng phạm vi: nhà cung cấp có bóc tách rõ khu vực và tần suất hay không? Tiếp theo là cách bố trí, thay thế và giám sát nhân sự.\n\nKiểm tra phương án máy móc, hóa chất, an toàn và cách tiếp nhận phản hồi. Cuối cùng, yêu cầu cách nghiệm thu và báo cáo được thể hiện rõ trong đề xuất.\n\nMột phương án tốt giúp người mua hiểu cách dịch vụ sẽ vận hành mỗi ngày, không chỉ biết tổng chi phí tháng.",
    meta: "{}",
    image: "/images/brand-insight-provider-checklist-v1.png",
    sortOrder: 2,
  }),
  record({
    id: "article-inhouse",
    type: "article",
    slug: "thue-dich-vu-hay-tu-to-chuc-nhan-su-ve-sinh",
    title: "Thuê dịch vụ hay tự tổ chức nhân sự vệ sinh?",
    eyebrow: "Quyết định vận hành",
    summary: "So sánh hai mô hình dựa trên khả năng điều phối, giám sát và tính ổn định thay vì nhìn vào lương cơ bản.",
    body: "Tự tổ chức phù hợp khi doanh nghiệp đã có năng lực tuyển dụng, đào tạo, thay ca, cấp phát vật tư và giám sát chuyên môn. Chi phí thực tế vì vậy không chỉ là tiền lương.\n\nThuê dịch vụ phù hợp khi cần một đầu mối chịu trách nhiệm về nhân sự và tiêu chuẩn thực hiện. Tuy nhiên phạm vi, cơ chế thay thế và báo cáo phải được ghi rõ.\n\nLựa chọn nên dựa trên mức độ kiểm soát nội bộ mong muốn, quy mô công trình và năng lực quản lý hiện có.",
    meta: "{}",
    image: "/images/brand-insight-workforce-model-v1.png",
    sortOrder: 3,
  }),
  record({
    id: "article-incident-response",
    type: "article",
    slug: "quy-trinh-xu-ly-su-vu-ve-sinh-toa-nha",
    title: "Quy trình xử lý sự vụ vệ sinh tòa nhà cần có gì?",
    eyebrow: "Kiểm soát sự vụ",
    summary: "Một quy trình tốt không dừng ở tiếp nhận phản ánh; nó phải làm rõ mức ưu tiên, người chịu trách nhiệm, trạng thái và cách ngăn vấn đề lặp lại.",
    body: "Trong vận hành tòa nhà, chất lượng dịch vụ không chỉ được nhìn thấy ở checklist hằng ngày mà còn ở cách đội ngũ phản ứng khi có sự vụ. Tràn nước, nguy cơ trượt ngã, phản ánh tại khu vực công cộng hoặc lỗi chất lượng lặp lại cần những cách ưu tiên khác nhau.\n\nMột luồng xử lý đầy đủ gồm năm dữ liệu cốt lõi: thời điểm và khu vực; mức ảnh hưởng; người phụ trách; hành động và trạng thái; kết quả xác nhận. Khi thông tin tập trung tại một đầu mối, ban quản lý không phải liên tục truy hỏi nhiều người để biết vấn đề đang ở đâu.\n\nBước cuối cùng là đóng vòng phản hồi. Nếu vấn đề có khả năng tái diễn, nhà cung cấp cần rà nguyên nhân và đề xuất thay đổi về tần suất, checklist, vật tư, hướng dẫn hoặc giám sát. Đây là điểm phân biệt giữa xử lý tình huống và cải thiện hệ thống.",
    meta: "{}",
    image: "/images/brand-insight-incident-response-v1.png",
    sortOrder: 4,
  }),
  ...[
    ["faq-scope", "pham-vi-dich-vu", "Phạm vi công việc được xác định như thế nào?", "AKAIUNSAN xác nhận loại công trình, khu vực, tần suất và tiêu chí bàn giao trước khi đề xuất phương án."],
    ["faq-survey", "khi-nao-can-khao-sat", "Khi nào cần khảo sát trực tiếp?", "Dự án chung cư, nhà xưởng và các công việc tổng vệ sinh nên được khảo sát để đánh giá bề mặt, luồng vận hành và yêu cầu an toàn."],
    ["faq-flexibility", "co-the-dieu-chinh-tan-suat", "Có thể điều chỉnh tần suất sau khi triển khai không?", "Có. Tần suất và phạm vi có thể được rà soát theo lưu lượng sử dụng, phản hồi vận hành và nhu cầu thực tế của từng giai đoạn."],
    ["faq-incidents", "su-vu-phat-sinh-duoc-xu-ly-ra-sao", "Sự vụ phát sinh được xử lý như thế nào?", "Sự vụ được ghi nhận theo khu vực và mức ảnh hưởng, phân loại ưu tiên, giao đầu mối điều phối, cập nhật trạng thái và chỉ đóng khi kết quả đã được xác nhận."],
  ].map(([id, slug, title, summary], index) =>
    record({
      id,
      type: "faq",
      slug,
      title,
      eyebrow: "Câu hỏi thường gặp",
      summary,
      body: summary,
      meta: "{}",
      image: null,
      sortOrder: index + 1,
    }),
  ),
];

const englishSeedContent: ContentRecord[] = [
  record({
    id: "en-service-recurring",
    translationKey: "service-recurring",
    locale: "en",
    type: "service",
    slug: "recurring-cleaning",
    title: "Recurring cleaning",
    eyebrow: "Core service",
    summary: "A stable daily, weekly, or shift-based schedule with scope and acceptance standards agreed from the start.",
    body: "Designed for shared building areas, condominium projects, factories that require shift coverage, and apartments that need dependable recurring support.\n\nAKAIUNSAN surveys the requirement, builds area-based checklists, assigns the team, and monitors service quality throughout delivery.",
    meta: JSON.stringify({
      highlights: ["Clear service schedule", "Area-based checklists", "Workforce coordination", "Monitoring and feedback"],
      cta: "Request a recurring cleaning plan",
    }),
    image: "/images/brand-category-condominium-v1.png",
    sortOrder: 1,
  }),
  record({
    id: "en-service-periodic",
    translationKey: "service-periodic",
    locale: "en",
    type: "service",
    slug: "periodic-cleaning",
    title: "Periodic cleaning",
    eyebrow: "Maintain quality",
    summary: "Scheduled deep-treatment tasks that protect surfaces, equipment, and the quality of occupied spaces.",
    body: "Periodic plans are designed around the property, usage intensity, and access constraints. Tasks, execution windows, and acceptance criteria are agreed before work begins.",
    meta: JSON.stringify({
      highlights: ["Weekly, monthly, or quarterly", "Specialist work packages", "Minimal operational disruption", "Clear acceptance criteria"],
      cta: "Discuss a periodic schedule",
    }),
    image: "/images/brand-category-industrial-v1.png",
    sortOrder: 2,
  }),
  record({
    id: "en-service-deep-clean",
    translationKey: "service-deep-clean",
    locale: "en",
    type: "service",
    slug: "deep-cleaning",
    title: "Deep cleaning",
    eyebrow: "Intensive cleaning",
    summary: "A project-based solution for apartments, handover areas, and properties that need a comprehensive reset.",
    body: "The scope is broken down by area, material, and current condition. The team selects the appropriate tools, chemicals, and work sequence before execution.",
    meta: JSON.stringify({
      highlights: ["Condition survey", "Material-specific scope", "Appropriate equipment", "Pre-handover inspection"],
      cta: "Request a deep-clean survey",
    }),
    image: "/images/brand-category-apartment-v1.png",
    sortOrder: 3,
  }),
  record({
    id: "en-solution-condominium",
    translationKey: "solution-condominium",
    locale: "en",
    type: "solution",
    slug: "building-condominium-cleaning",
    title: "Building & condominium cleaning",
    eyebrow: "Building operations",
    summary: "Teams and schedules organized around resident traffic, acceptance standards, and the needs of property management.",
    body: "A solution for lobbies, corridors, lifts, amenities, and other common areas. Shift scopes are standardized so the cleaning team can coordinate with building operations and minimize disruption to occupants.\n\nReporting, field feedback, and additional work requests are coordinated through one service contact.",
    meta: JSON.stringify({
      highlights: ["Lobbies and corridors", "Lifts and amenities", "Schedules based on occupant traffic", "Supervision and feedback"],
      cta: "Request a building survey",
      leadType: "building",
    }),
    image: "/images/brand-category-condominium-v1.png",
    sortOrder: 1,
  }),
  record({
    id: "en-solution-factory",
    translationKey: "solution-factory",
    locale: "en",
    type: "solution",
    slug: "factory-industrial-cleaning",
    title: "Factory & industrial cleaning",
    eyebrow: "Production environments",
    summary: "A cleaning plan aligned with site zones, production shifts, and the safety requirements of each facility.",
    body: "Factories require different methods for walkways, support areas, warehouses, production offices, and controlled zones. AKAIUNSAN reviews operational flows before proposing people, equipment, and frequency.\n\nSafety rules, permitted work areas, and coordination with the facility contact are defined before launch.",
    meta: JSON.stringify({
      highlights: ["Walkways and support areas", "Production-shift schedules", "Industrial equipment", "Site safety compliance"],
      cta: "Request a factory survey",
      leadType: "factory",
    }),
    image: "/images/brand-category-industrial-v1.png",
    sortOrder: 2,
  }),
  record({
    id: "en-solution-apartment",
    translationKey: "solution-apartment",
    locale: "en",
    type: "solution",
    slug: "apartment-cleaning",
    title: "Apartment cleaning",
    eyebrow: "Living spaces",
    summary: "Flexible one-off or recurring service delivered with care for private spaces and household schedules.",
    body: "Every apartment has a different size, material mix, and usage pattern. AKAIUNSAN confirms the scope before each visit, prioritizes important areas, and hands the space back against a checklist.\n\nSuitable for weekly support, a fixed recurring schedule, or a one-time deep clean.",
    meta: JSON.stringify({
      highlights: ["Living rooms and bedrooms", "Kitchen and working surfaces", "Bathrooms", "Balconies by agreement"],
      cta: "Book apartment cleaning",
      leadType: "apartment",
    }),
    image: "/images/brand-category-apartment-v1.png",
    sortOrder: 3,
  }),
  ...[
    ["incident-capture", "capture-the-full-context", "Capture the full context", "Triage", "Confirm time, location, impact, reporter, and relevant field evidence before deciding what must happen."],
    ["incident-prioritize", "prioritize-by-impact", "Prioritize by impact", "Priority", "Handle safety risks and operational disruption before ordinary appearance or quality issues."],
    ["incident-coordinate", "coordinate-and-update", "Coordinate and update", "Ownership", "Name one coordinator, the next action, and a visible status so the customer does not have to chase information."],
    ["incident-close-loop", "close-the-loop", "Close the loop", "Resolution", "Confirm the outcome, record the cause, and change the checklist, materials, training, or SOP when recurrence is likely."],
  ].map(([translationKey, slug, title, eyebrow, summary], index) => record({
    id: `en-${translationKey}`,
    translationKey,
    locale: "en",
    type: "incident",
    slug,
    title,
    eyebrow,
    summary,
    body: summary,
    meta: "{}",
    image: null,
    sortOrder: index + 1,
  })),
  record({
    id: "en-article-cost",
    translationKey: "article-cost",
    locale: "en",
    type: "article",
    slug: "how-cleaning-service-quotes-are-calculated",
    title: "How is a professional cleaning quote calculated?",
    eyebrow: "Cost & scope",
    summary: "Area is only one input; frequency, materials, shift windows, and equipment requirements shape the right plan.",
    body: "A responsible quote starts with the work scope, not square meters alone. The provider needs to understand surfaces, usage density, permitted work windows, safety requirements, and acceptance criteria.\n\nFor buildings and factories, the operating model also includes shifts, occupant flow, machinery, and workforce organization. In apartments, room count and current condition influence the time required.\n\nA survey lets both parties agree what is included, how often it is done, and how exceptions are handled before price is finalized.",
    meta: "{}",
    image: "/images/brand-insight-pricing-scope-v1.png",
    sortOrder: 1,
  }),
  record({
    id: "en-article-checklist",
    translationKey: "article-checklist",
    locale: "en",
    type: "article",
    slug: "cleaning-vendor-evaluation-checklist",
    title: "A practical checklist for evaluating a cleaning provider",
    eyebrow: "Vendor selection",
    summary: "Questions that help building and factory teams assess operating capability—not only compare monthly prices.",
    body: "Start with scope: does the provider clearly define areas and frequency? Then review how people are assigned, replaced, trained, and supervised.\n\nCheck the plan for equipment, chemicals, safety, and feedback handling. Finally, ask how acceptance and reporting will work in practice.\n\nA strong proposal shows how the service will operate every day, not only the monthly total.",
    meta: "{}",
    image: "/images/brand-insight-provider-checklist-v1.png",
    sortOrder: 2,
  }),
  record({
    id: "en-article-inhouse",
    translationKey: "article-inhouse",
    locale: "en",
    type: "article",
    slug: "outsourced-vs-in-house-cleaning",
    title: "Outsourced or in-house cleaning: which model fits?",
    eyebrow: "Operating decision",
    summary: "Compare the models through coordination, supervision, and continuity—not basic salary alone.",
    body: "An in-house model works when the organization already has the capacity to recruit, train, cover absences, issue supplies, and supervise cleaning quality. The true cost is therefore more than payroll.\n\nOutsourcing works when one provider must take responsibility for people and delivery standards. Scope, replacement coverage, and reporting still need to be explicit.\n\nThe decision should reflect the desired level of internal control, site scale, and current management capacity.",
    meta: "{}",
    image: "/images/brand-insight-workforce-model-v1.png",
    sortOrder: 3,
  }),
  record({
    id: "en-article-incident-response",
    translationKey: "article-incident-response",
    locale: "en",
    type: "article",
    slug: "building-cleaning-incident-response",
    title: "What should a building cleaning incident process include?",
    eyebrow: "Service recovery",
    summary: "A complete process clarifies priority, ownership, status, confirmation, and how repeat issues will be prevented.",
    body: "In building operations, service quality is visible not only in the daily checklist but also in the response when conditions change. Water spills, slip risks, common-area complaints, and repeat quality failures require different levels of priority.\n\nA complete workflow captures five essentials: time and area, impact level, responsible owner, action and status, and confirmed outcome. One source of truth means property management does not have to chase multiple people for an update.\n\nThe final step closes the feedback loop. When recurrence is possible, the provider reviews the cause and proposes changes to frequency, checklists, materials, instructions, or supervision.",
    meta: "{}",
    image: "/images/brand-insight-incident-response-v1.png",
    sortOrder: 4,
  }),
  ...[
    ["faq-scope", "how-service-scope-is-defined", "How is the service scope defined?", "AKAIUNSAN confirms the property type, areas, frequency, and acceptance criteria before proposing a plan."],
    ["faq-survey", "when-an-onsite-survey-is-needed", "When is an on-site survey required?", "Buildings, factories, and deep-cleaning projects should be surveyed to assess surfaces, operating flows, and safety requirements."],
    ["faq-flexibility", "can-frequency-change", "Can the frequency change after launch?", "Yes. Frequency and scope can be reviewed against usage levels, operating feedback, and the needs of each phase."],
    ["faq-incidents", "how-service-incidents-are-handled", "How are service incidents handled?", "Each incident is captured with its area and impact, prioritized, assigned to a coordinator, updated, and closed only after the outcome is confirmed."],
  ].map(([translationKey, slug, title, summary], index) => record({
    id: `en-${translationKey}`,
    translationKey,
    locale: "en",
    type: "faq",
    slug,
    title,
    eyebrow: "Frequently asked questions",
    summary,
    body: summary,
    meta: "{}",
    image: null,
    sortOrder: index + 1,
  })),
];

export const seedContent: ContentRecord[] = [...vietnameseSeedContent, ...englishSeedContent];

export const seedSettings: Record<string, string> = {
  siteName: "AKAIUNSAN",
  tagline: "Professional Cleaning Solutions",
  promise: "Sạch đúng chuẩn. Vận hành đúng cam kết.",
  phone: "",
  email: "",
  address: "",
};

export const seedMedia = [
  {
    id: "media-apartment",
    title: "Vệ sinh căn hộ — ảnh minh họa",
    objectKey: null,
    publicPath: "/images/brand-category-apartment-v1.png",
    altText: "Nhân viên vệ sinh chuyên nghiệp đang làm sạch căn hộ",
    sourceType: "ai-generated",
    sourceReference: "OpenAI ImageGen, 2026-08-06 — apartment category",
    category: "apartment",
    isPlaceholder: false,
    mimeType: "image/png",
    width: 1536,
    height: 1024,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "media-condominium",
    title: "Vệ sinh chung cư — ảnh minh họa",
    objectKey: null,
    publicPath: "/images/brand-category-condominium-v1.png",
    altText: "Đội vệ sinh vận hành khu vực chung của dự án chung cư",
    sourceType: "ai-generated",
    sourceReference: "OpenAI ImageGen, 2026-08-06 — condominium category",
    category: "condominium",
    isPlaceholder: false,
    mimeType: "image/png",
    width: 1536,
    height: 1024,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "media-factory",
    title: "Vệ sinh nhà xưởng — ảnh minh họa",
    objectKey: null,
    publicPath: "/images/brand-category-industrial-v1.png",
    altText: "Đội vệ sinh công nghiệp làm việc an toàn trong nhà xưởng",
    sourceType: "ai-generated",
    sourceReference: "OpenAI ImageGen, 2026-08-06 — industrial category",
    category: "factory",
    isPlaceholder: false,
    mimeType: "image/png",
    width: 1536,
    height: 1024,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "media-insight-pricing-scope",
    title: "Báo giá theo phạm vi — ảnh bài viết",
    objectKey: null,
    publicPath: "/images/brand-insight-pricing-scope-v1.png",
    altText: "Quản lý cơ sở và giám sát vệ sinh rà soát phạm vi công việc trên máy tính bảng",
    sourceType: "ai-generated",
    sourceReference: "OpenAI ImageGen, 2026-08-06 — pricing and scope insight",
    category: "article",
    isPlaceholder: false,
    mimeType: "image/png",
    width: 1536,
    height: 1024,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "media-insight-provider-checklist",
    title: "Đánh giá nhà cung cấp — ảnh bài viết",
    objectKey: null,
    publicPath: "/images/brand-insight-provider-checklist-v1.png",
    altText: "Quản lý nhà máy và giám sát vệ sinh thực hiện kiểm tra hiện trường",
    sourceType: "ai-generated",
    sourceReference: "OpenAI ImageGen, 2026-08-06 — provider checklist insight",
    category: "article",
    isPlaceholder: false,
    mimeType: "image/png",
    width: 1536,
    height: 1024,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "media-insight-workforce-model",
    title: "Mô hình nhân sự vệ sinh — ảnh bài viết",
    objectKey: null,
    publicPath: "/images/brand-insight-workforce-model-v1.png",
    altText: "Quản lý cơ sở trao đổi kế hoạch ca làm với đội ngũ vệ sinh chuyên nghiệp",
    sourceType: "ai-generated",
    sourceReference: "OpenAI ImageGen, 2026-08-06 — workforce model insight",
    category: "article",
    isPlaceholder: false,
    mimeType: "image/png",
    width: 1536,
    height: 1024,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "media-insight-incident-response",
    title: "Xử lý sự vụ vệ sinh — ảnh bài viết",
    objectKey: null,
    publicPath: "/images/brand-insight-incident-response-v1.png",
    altText: "Đội vệ sinh cô lập và xử lý sự cố tràn nước tại hành lang tòa nhà",
    sourceType: "ai-generated",
    sourceReference: "OpenAI ImageGen, 2026-08-06 — incident response insight",
    category: "article",
    isPlaceholder: false,
    mimeType: "image/png",
    width: 1536,
    height: 1024,
    createdAt: now,
    updatedAt: now,
  },
];
